### ISSUE TITLE
Unable to install git version

### ISSUE THREAD

**Issue by pablo-aledo** [sosy-lab/benchexec#112]
Hi, I'm trying to install the git-version of benchexec with the following command 

pip3 install --user git+https://github.com/sosy-lab/benchexec.git

However, I obtain this error, which I don't fully understand:

```
Downloading/unpacking git+https://github.com/sosy-lab/benchexec.git
  Cloning https://github.com/sosy-lab/benchexec.git to /tmp/pip-0hi2gv95-build
  Running setup.py (path:/tmp/pip-0hi2gv95-build/setup.py) egg_info for package from git+https://github.com/sosy-lab/benchexec.git
    no previously-included directories found matching 'doc/.build'
    warning: build_py: byte-compiling is disabled, skipping.
    
    warning: install_lib: byte-compiling is disabled, skipping.
    
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-0hi2gv95-build/setup.py", line 87, in <module>
        zip_safe = True,
      File "/usr/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 239, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs
        replace_conflicting=True
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 620, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 858, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/usr/lib/python3/dist-packages/pkg_resources.py", line 870, in obtain
        return installer(requirement)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1045, in build_and_install
        eggs.append(self.install_egg(dist.location, setup_base))
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 871, in install_egg
        (os.path.basename(egg_path),os.path.dirname(destination)))
      File "/usr/lib/python3.4/distutils/cmd.py", line 336, in execute
        util.execute(func, args, msg, dry_run=self.dry_run)
      File "/usr/lib/python3.4/distutils/util.py", line 301, in execute
        func(*args)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1131, in unpack_and_compile
        self.byte_compile(to_compile)
      File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1147, in byte_compile
        byte_compile(to_compile, optimize=0, force=1, dry_run=self.dry_run)
      File "/usr/lib/python3.4/distutils/util.py", line 355, in byte_compile
        raise DistutilsByteCompileError('byte-compiling is disabled.')
    distutils.errors.DistutilsByteCompileError: byte-compiling is disabled.
    Complete output from command python setup.py egg_info:
    no previously-included directories found matching 'doc/.build'

warning: build_py: byte-compiling is disabled, skipping.



warning: install_lib: byte-compiling is disabled, skipping.



Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-0hi2gv95-build/setup.py", line 87, in <module>

    zip_safe = True,

  File "/usr/lib/python3.4/distutils/core.py", line 108, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 239, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 264, in fetch_build_eggs

    replace_conflicting=True

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 620, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 858, in best_match

    return self.obtain(req, installer) # try and download/install

  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 870, in obtain

    return installer(requirement)

  File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 314, in fetch_build_egg

    return cmd.easy_install(req)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 646, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1045, in build_and_install

    eggs.append(self.install_egg(dist.location, setup_base))

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 871, in install_egg

    (os.path.basename(egg_path),os.path.dirname(destination)))

  File "/usr/lib/python3.4/distutils/cmd.py", line 336, in execute

    util.execute(func, args, msg, dry_run=self.dry_run)

  File "/usr/lib/python3.4/distutils/util.py", line 301, in execute

    func(*args)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1131, in unpack_and_compile

    self.byte_compile(to_compile)

  File "/usr/lib/python3/dist-packages/setuptools/command/easy_install.py", line 1147, in byte_compile

    byte_compile(to_compile, optimize=0, force=1, dry_run=self.dry_run)

  File "/usr/lib/python3.4/distutils/util.py", line 355, in byte_compile

    raise DistutilsByteCompileError('byte-compiling is disabled.')

distutils.errors.DistutilsByteCompileError: byte-compiling is disabled.

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-0hi2gv95-build
Storing debug log for failure in /home/mint/.pip/pip.log
```

Can someone help me with this issue?.

Regards.

**Comment by PhilippWendler** [comment]
Hello, I have not seen such an error before, and it seems more like a Python problem than a BenchExec problem.
I also cannot reproduce it, your command works fine on my machine.

Is there any helpful information in the debug log file that is mentioned in the output?
Maybe you could try installing BenchExec in a [virtualenv](http://docs.python-guide.org/en/latest/dev/virtualenvs/)?

**Comment by pablo-aledo** [comment]
Hi, thanks for the quick answer.
To make the issue more reproducible I've started with a fresh version of Ubuntu Server 14.04 LTS. This has changed the environment, so I don't know if it would be better to start a new issue.

The only modifications that I've performed to the base install can be summarized as:

sudo apt-get install python3-pip
sudo apt-get install git
sudo apt-get install libxml2-dev
sudo apt-get install libxslt1-dev
sudo ln -s /usr/bin/gcc /usr/bin/x86_64-linux-gnu-gcc
sudo ln -s /usr/bin/gcc /bin/x86_64-linux-gnu-gcc
export PATH=/usr/bin/:$PATH

pip3 install --user git+https://github.com/sosy-lab/benchexec.git

the output .pip/pip.log can be found here http://pastebin.com/tExdvHxS

**Comment by PhilippWendler** [comment]
In that log, your compiler fails because it cannot find `-lz`, so it seems `zlib1g-dev` is missing. This should not be needed for installing BenchExec, however (in fact, you should not even need a C compiler).

Probably this is because the `lxml` Python module is missing, so pip tries to install it manually, which produces all these dependencies. I suggest trying to install `python3-lxml`, then hopefully there is nothing left that needs to be compiled. If this works, please tell me, then I can add a note for others in the documentation.

**Comment by pablo-aledo** [comment]
I've installed python3-lxml. Effectively, it looks like there's no more compilation issues, but I get the following errors:
http://pastebin.com/nGcLyip8

**Comment by PhilippWendler** [comment]
So we are back to the original problem. I still have no idea what is different on your machine than on mine, but after looking at the source code of Python's distutils that is referenced in the stack trace I think I have found a workaround. Could you please try installing from branch `DistutilsByteCompileError` with 

    pip3 install --user git+https://github.com/sosy-lab/benchexec.git@DistutilsByteCompileError

If it works, I will integrated this into the master branch and delete the temporary branch, so you would need to install from the master branch again the next time you want to update your BenchExec version.

**Comment by pablo-aledo** [comment]
Hi Philipp. The fix solved the issue and benchexec now compiles without any error using the branch.

Thanks a lot :smile:
