### ISSUE TITLE
Preferred way of handling missing features from tool-info module

### ISSUE THREAD

**Issue by danieldietsch** [sosy-lab/benchexec#359]
The tool-info modules for the Ultimate tools do not support all features and probably never will. 
This is currently handled by raising a ``NameError`` in the module if the supplied options cannot be handled. 
During ``test_tool_info``, this leads to output that contains tracebacks for the missing features. 
Is there any way to indicate that these features are not buggy but merely missing that also suppresses these tracebacks?
````
# PYTHONPATH=/storage/benchexec/ python3 -m benchexec.test_tool_info ultimatetaipan
Name of tool module: “ultimatetaipan”
Full name of tool module: “benchexec.tools.ultimatetaipan”
Documentation of tool module:
        This is the tool info module for ULTIMATE Taipan.

        You can download the latest release from GitHub or build the latest development snapshot by following the
        instructions at https://github.com/ultimate-pa/ultimate/wiki/Usage

        Please report any issues to our issue tracker at https://github.com/ultimate-pa/ultimate/issues

        Latest release: https://github.com/ultimate-pa/ultimate/releases/latest
        Git repository: https://github.com/ultimate-pa/ultimate.git
Name of tool: “ULTIMATE Taipan”
Executable: “./Ultimate.py”
Executable (absolute path): “/storage/ultimate/releaseScripts/default/UAutomizer-linux/Ultimate.py”
Version: “0.1.23-822e86c7”
Working directory: “.”
Working directory (absolute path): “/storage/ultimate/releaseScripts/default/UAutomizer-linux”
Program files:
        “./Ultimate.py”
        “artifacts.xml”
        “config”
        “configuration”
        “cvc4”
        “cvc4nyu”
        “cvc4-LICENSE”
        “features”
        “LICENSE”
        “LICENSE.GPL”
        “LICENSE.GPL.LESSER”
        “mathsat”
        “p2”
        “plugins”
        “README”
        “Ultimate”
        “Ultimate.ini”
        “Ultimate.py”
        “z3”
        “z3-LICENSE”
Program files (absolute paths):
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/Ultimate.py”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/artifacts.xml”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/config”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/configuration”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/cvc4”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/cvc4nyu”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/cvc4-LICENSE”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/features”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/LICENSE”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/LICENSE.GPL”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/LICENSE.GPL.LESSER”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/mathsat”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/p2”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/plugins”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/README”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/Ultimate”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/Ultimate.ini”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/Ultimate.py”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/z3”
        “/storage/ultimate/releaseScripts/default/UAutomizer-linux/z3-LICENSE”
WARNING: Tool module does not support tasks without options, property file, and resource limits:
Traceback (most recent call last):
  File "/storage/benchexec/benchexec/test_tool_info.py", line 128, in print_tool_info
    cmdline = model.cmdline_for_run(tool, executable, [], ['INPUT.FILE'], None, {})
  File "/storage/benchexec/benchexec/model.py", line 134, in cmdline_for_run
    rlimits.copy())
  File "/storage/benchexec/benchexec/tools/ultimate.py", line 240, in cmdline
    raise NameError("Unsupported argument combination")
NameError: Unsupported argument combination
WARNING: Tool module does not support tasks with command-line options:
Traceback (most recent call last):
  File "/storage/benchexec/benchexec/test_tool_info.py", line 138, in print_tool_info
    cmdline = model.cmdline_for_run(tool, executable, ['-SOME_OPTION'], ['INPUT.FILE'], None, {})
  File "/storage/benchexec/benchexec/model.py", line 134, in cmdline_for_run
    rlimits.copy())
  File "/storage/benchexec/benchexec/tools/ultimate.py", line 240, in cmdline
    raise NameError("Unsupported argument combination")
NameError: Unsupported argument combination
Command line with property file:
        “['./Ultimate.py', '--spec', 'PROPERTY.PRP', '--file', 'INPUT.FILE']”
WARNING: Tool module does not support tasks with multiple input files:
Traceback (most recent call last):
  File "/storage/benchexec/benchexec/test_tool_info.py", line 155, in print_tool_info
    cmdline = model.cmdline_for_run(tool, executable, [], ['INPUT1.FILE', 'INPUT2.FILE'], None, {})
  File "/storage/benchexec/benchexec/model.py", line 134, in cmdline_for_run
    rlimits.copy())
  File "/storage/benchexec/benchexec/tools/ultimate.py", line 240, in cmdline
    raise NameError("Unsupported argument combination")
NameError: Unsupported argument combination
WARNING: Tool module does not support tasks with CPU-time limit:
Traceback (most recent call last):
  File "/storage/benchexec/benchexec/test_tool_info.py", line 164, in print_tool_info
    cmdline = model.cmdline_for_run(tool, executable, [], ['INPUT.FILE'], None, {model.SOFTTIMELIMIT: 123})
  File "/storage/benchexec/benchexec/model.py", line 134, in cmdline_for_run
    rlimits.copy())
  File "/storage/benchexec/benchexec/tools/ultimate.py", line 240, in cmdline
    raise NameError("Unsupported argument combination")
NameError: Unsupported argument combination
````

**Comment by PhilippWendler** [comment]
I know that this is not optimal, and precisely because such features are optional and do not need to be supported the `test_tool_info` utility only warns about it instead of producing an error.

A [`NameError`](https://docs.python.org/3/library/exceptions.html#NameError) though is certainly not the correct solution, as this error has defined semantics that do not fit here.

We could add a convention to BenchExec what tool-info modules should do in such a case, and omit the stack trace. Probably the best is to expect `BenchExecException`, what do you think about this?

**Comment by danieldietsch** [comment]
Works for me -- I can convert all the exceptions to this one. But perhaps one should have some derived exception, perhaps something like ``UnsupportedToolInfoFeatureException``. It would avoid collisions with other usages of BenchExecExceptions that are legitimate in this context.

**Comment by PhilippWendler** [comment]
Good idea. I implemented this, have a look at it and if you have any feedback I would be glad to here it.

Both `benchexec` as well as `test_tool_info` will not hide stack traces if such an exception is thrown.
