### ISSUE TITLE
Certain characters in environment variables can crash BenchExec

### ISSUE THREAD

**Issue by PhilippWendler** [sosy-lab/benchexec#366]
In this [CI job](https://gitlab.com/sosy-lab/software/sv-benchmarks/-/jobs/121134727), BenchExec crashed while writing the final result XML file with this stacktrace:
```
Traceback (most recent call last):
  File "/usr/local/bin/benchexec", line 11, in <module>
    load_entry_point('BenchExec==1.17.dev0', 'console_scripts', 'benchexec')()
  File "/usr/local/lib/python3.6/dist-packages/benchexec/benchexec.py", line 362, in main
    sys.exit(benchexec.start(argv or sys.argv))
  File "/usr/local/lib/python3.6/dist-packages/benchexec/benchexec.py", line 80, in start
    rc = self.execute_benchmark(arg)
  File "/usr/local/lib/python3.6/dist-packages/benchexec/benchexec.py", line 285, in execute_benchmark
    result = self.executor.execute_benchmark(benchmark, output_handler)
  File "/usr/local/lib/python3.6/dist-packages/benchexec/localexecution.py", line 195, in execute_benchmark
    output_handler.output_after_run_set(runSet, cputime=usedCpuTime, walltime=usedWallTime, energy=energy)
  File "/usr/local/lib/python3.6/dist-packages/benchexec/outputhandler.py", line 495, in output_after_run_set
    self._write_pretty_result_xml_to_file(runSet.xml, runSet.xml_file_name)
  File "/usr/local/lib/python3.6/dist-packages/benchexec/outputhandler.py", line 746, in _write_pretty_result_xml_to_file
    reparsed = minidom.parseString(rough_string)
  File "/usr/lib/python3.6/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.6/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.6/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 5296-5299: surrogates not allowed
```
Probable cause is the emoji 🤖 which was part of an environment variable.

**Comment by PhilippWendler** [comment]
I ran benchexec after `export TEST="🤖"`, and it worked (Python 3.6, Ubuntu 18.04). I also confirmed that the emoji was correctly represented in the result XML file.

So I cannot reproduce this currently.
