### ISSUE TITLE
Failure to write zip file

### ISSUE THREAD

**Issue by tautschnig** [sosy-lab/benchexec#389]
Running on Ubuntu 18.04 I just got the following:
```
../benchexec/bin/benchexec cbmc.xml --no-container --task ReachSafety-ECA -T 900s -M 15GB -o logs-ReachSafety-ECA/ -N 24 -c 1
2018-12-19 10:29:36,963 - WARNING - The selected tasks "ReachSafety-ECA" are not present in the input file, skipping them.
2018-12-19 10:29:36,963 - WARNING - The selected tasks "ReachSafety-ECA" are not present in the input file, skipping them.
2018-12-19 10:29:36,963 - WARNING - The selected tasks "ReachSafety-ECA" are not present in the input file, skipping them.
2018-12-19 10:29:36,988 - WARNING - Ignoring specified resource requirements in local-execution mode, only resource limits are used.

executing run set 'sv-comp19_prop-reachsafety.ReachSafety-ECA'     (1256 files)
10:29:37   starting   eca-rers2012/Problem01_label15_false-unreach-call_false-termination.c
10:29:37   starting   eca-rers2012/Problem01_label20_false-unreach-call_false-termination.c
10:29:37   starting   eca-rers2012/Problem01_label21_false-unreach-call_false-termination.c
10:29:37   starting   eca-rers2012/Problem01_label32_false-unreach-call_false-termination.c
10:29:37   starting   eca-rers2012/Problem01_label33_false-unreach-call_false-termination.c
10:29:37   starting   eca-rers2012/Problem01_label35_false-unreach-call_false-termination.c
10:29:37   starting   eca-rers2012/Problem01_label37_false-unreach-call_false-termination.c
[...] (several more successful and some failing with the same error message as below)
2018-12-19 10:29:42,682 - ERROR - Exception during run execution
Traceback (most recent call last):
  File "../benchexec/bin/../benchexec/localexecution.py", line 249, in run
    self.execute(currentRun)
  File "../benchexec/bin/../benchexec/localexecution.py", line 307, in execute
    self.output_handler.output_after_run(run)
  File "../benchexec/bin/../benchexec/outputhandler.py", line 477, in output_after_run
    self.log_zip.write(run.log_file, os.path.relpath(run.log_file, os.path.join(self.benchmark.log_folder, os.pardir)))
  File "/usr/lib/python3.6/zipfile.py", line 1614, in write
    "Can't write to ZIP archive while an open writing handle exists"
ValueError: Can't write to ZIP archive while an open writing handle exists
```

I'm not sure how locking of the zip file is handled, but it seems the 24 concurrent executions pose some problem.

**Comment by PhilippWendler** [comment]
> I'm not sure how locking of the zip file is handled

Well, it's not :-)

I don't have a machine with so many cores so it's hard for me to test the fix. Could you please test it with branch `zip_lock`?

**Comment by tautschnig** [comment]
Thanks a lot for the immediate fix, I'm running a test now and will report back.

**Comment by tautschnig** [comment]
My tests are still running, but the zip issue certainly seems to have gone away. I'm now just waiting for the final results to make sure there isn't any other regression.

**Comment by tautschnig** [comment]
I can confirm that the run was successful, and a good zip archive of log files is produced. Thanks again for the immediate fix!!

**Comment by PhilippWendler** [comment]
Thanks for reporting and testing!
