### ISSUE TITLE
Table-generator fails with no options attribute, although it should be optional

### ISSUE THREAD

**Issue by onderjan** [sosy-lab/benchexec#922]
Writing a custom generator of XML input files for table-generator 3.16 (current Ubuntu PPA version), I found that table-generator does not correctly work for some input files that follow the benchexec result DTD ( https://www.sosy-lab.org/benchexec/result-3.0.dtd ). The "options" attribute of "result" element is not required in DTD, but without it, table-generator throws an error. Minimal example:
```
<?xml version = "1.0" encoding = "UTF-8"?>
<result tool="(tool)" toolmodule="(tool)" version="(unknown)" benchmarkname="(unknown)" starttime="(unknown)" date="(unknown)" generator="(generator)">
	<systeminfo>
		<os name="(unknown)" />
		<cpu cores="(unknown)" frequency="(unknown)" model="(unknown)" />
		<ram size="(unknown)" />
		<environment />
	</systeminfo>
	<run name="run1.yml" expectedVerdict="false">
		<column title="status" value="TIMEOUT" />
		<column title="category" value="error" />
		<column title="cputime" value="1010.020000s" />
		<column title="walltime" value="1007.980000s" />
		<column title="memory" value="1569988608B" />
	</run>
</result>
```
Table-generator output:
```
INFO:     options-bug.xml
INFO: Merging results...
INFO: The resulting table will have 1 rows and 5 columns (in 1 run sets).
INFO: Generating table...
INFO: Writing HTML into ./options-bug.html ...
INFO: Writing CSV  into ./options-bug.csv ...
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/__init__.py", line 1376, in write_table_in_format
    callback(out, options=options, **kwargs)
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/htmltable.py", line 38, in write_html_table
    benchmark_setup = _prepare_benchmark_setup_data(
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/htmltable.py", line 203, in _prepare_benchmark_setup_data
    "options": get_row("Options", "{options}"),
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/htmltable.py", line 145, in get_row
    values = [
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/htmltable.py", line 146, in <listcomp>
    format_cell(runSetResult.attributes) for runSetResult in runSetResults
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/htmltable.py", line 143, in format_cell
    return formatStr.format(**attributes)
KeyError: 'options'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/table-generator", line 33, in <module>
    sys.exit(load_entry_point('BenchExec==3.16', 'console_scripts', 'table-generator')())
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/__init__.py", line 1728, in main
    f.result()  # to get any exceptions that may have occurred
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
KeyError: 'options'
Exception ignored in: <function _ExecutorManagerThread.__init__.<locals>.weakref_cb at 0x7f46e8766680>
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 288, in weakref_cb
AttributeError: 'NoneType' object has no attribute 'debug'
```
Adding the options attribute (even empty), table generator works properly:
```
(...)
<result tool="(tool)" toolmodule="(tool)" version="(unknown)" benchmarkname="(unknown)" starttime="(unknown)" date="(unknown)" generator="(generator)" options="">
(...)
```

I do not know if this behaviour can be triggered by XML files generated by benchexec itself.

In addition to fixing the bug, it might be advisable to check the input XML files for valid DTD beforehand to avoid unhandled exceptions except in cases of actual programming errors, although it could degrade the performance of table-generator.

**Comment by PhilippWendler** [comment]
> In addition to fixing the bug, it might be advisable to check the input XML files for valid DTD beforehand to avoid unhandled exceptions except in cases of actual programming errors, although it could degrade the performance of table-generator.

Would be nice and is tracked as #392, but the built-in XML parsers in Python do not provide this and we do not want to require a library as a dependency.
