### ISSUE TITLE
Table-generator fails for floating-point numbers with too many digits

### ISSUE THREAD

**Issue by onderjan** [sosy-lab/benchexec#923]
Table-generator fails because of the cputime value generated by default conversion of 64-bit float value to string in rustc 1.70.0:
```
<?xml version = "1.0" encoding = "UTF-8"?>
<result tool="(tool)" toolmodule="(tool)" version="(unknown)" benchmarkname="(unknown)" starttime="(unknown)" date="(unknown)" generator="(generator)" options="">
	<systeminfo>
		<os name="(unknown)" />
		<cpu cores="(unknown)" frequency="(unknown)" model="(unknown)" />
		<ram size="(unknown)" />
		<environment />
	</systeminfo>
	<run name="goel-crafted/sw_loop.yml" expectedVerdict="true">
		<column title="status" value="true" />
		<column title="category" value="correct" />
		<column title="cputime" value="0.09999999999999999s" />
		<column title="walltime" value="0.11s" />
		<column title="memory" value="44662784B" />
	</run>
</result>

```
INFO:     float-bug.xml
INFO: Merging results...
INFO: The resulting table will have 1 rows and 5 columns (in 1 run sets).
INFO: Generating table...
INFO: Writing HTML into ./float-bug.html ...
INFO: Writing CSV  into ./float-bug.csv ...
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/__init__.py", line 1376, in write_table_in_format
    callback(out, options=options, **kwargs)
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/htmltable.py", line 42, in write_html_table
    stats = _prepare_stats(stats, rows, columns)
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/htmltable.py", line 316, in _prepare_stats
    add_stat_row("total", description=task_counts)
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/htmltable.py", line 302, in add_stat_row
    content = [
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/htmltable.py", line 303, in <listcomp>
    [
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/htmltable.py", line 304, in <listcomp>
    _convert_statvalue_to_json(column_stats, field, column)
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/htmltable.py", line 262, in _convert_statvalue_to_json
    return {
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/htmltable.py", line 263, in <dictcomp>
    k: format_stat_value(k, v)
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/htmltable.py", line 251, in format_stat_value
    return column.format_value(value, "html_cell")
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/columns.py", line 261, in format_value
    return _format_number(
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/columns.py", line 388, in _format_number
    assert number.adjusted() == int(floor(log10(abs(number))))
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/table-generator", line 33, in <module>
    sys.exit(load_entry_point('BenchExec==3.16', 'console_scripts', 'table-generator')())
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/__init__.py", line 1728, in main
    f.result()  # to get any exceptions that may have occurred
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
AssertionError
Exception ignored in: <function _ExecutorManagerThread.__init__.<locals>.weakref_cb at 0x7fce9a1b2680>
Traceback (most recent call last):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 288, in weakref_cb
AttributeError: 'NoneType' object has no attribute 'debug'
```
After removing the last 9 in the cputime value, table-generator no longer fails. Investigating further, trying out going to next smaller representable number (this is currently only supported in nightly Rust behind a feature gate, you could also do it e.g. in C by reinterpretation)
```
#![feature(float_next_up_down)]
fn main() {
    let d: f64 = 0.09999999999999999;
    println!("{}", d);
    println!("{}", d.next_down());
}
```
prints
```
0.09999999999999999
0.09999999999999998
```
Using the ...98 number also fails, so the printing precision is correct. Looking at the trace, the assertion
```
  File "/usr/lib/python3/dist-packages/benchexec/tablegenerator/columns.py", line 388, in _format_number
    assert number.adjusted() == int(floor(log10(abs(number))))
```
is to blame, not Python itself. The assertion seems highly suspect as it  So this seems to be table-generator-specific bug. It seems possible that XML files generated by benchexec could also run into this problem if maximum precision is not adjusted when printing.

Looking at the _format_number routine, it seems highly suspect to me. I'm not sure why a custom routine is used instead of system ones (I'm not very familiar with Python though), but it doesn't inspire confidence.

**Comment by PhilippWendler** [comment]
Interesting case. Here we reached the limit of the precision of the `log10` function of Python. But luckily we can easily switch to another log10 function for our specific number type, which is more precise.

> The assertion seems highly suspect as it

Hm, I wonder why? So far, it never failed, and (after fixing the rounding problem leading to this bug) also works for this input number.

> Looking at the _format_number routine, it seems highly suspect to me. I'm not sure why a custom routine is used instead of system ones (I'm not very familiar with Python though), but it doesn't inspire confidence.

Well, there simply isn't an existing formatting routine that allows specifying a fixed number of significant digits and produces decimal output, not scientific notation.
