### ISSUE TITLE
Benchexec hangs in recent versions of Docker Desktop

### ISSUE THREAD

**Issue by ysabih2** [sosy-lab/benchexec#985]
I have been using Benchexec in Docker containers for sandboxing for a while, but it stopped working after I upgraded to recent versions of Docker Desktop. The container is based on `mcr.microsoft.com/dotnet/sdk:6.0-focal`. It's executed with `--privileged` option and the volume mount `/sys/fs/cgroup`. When I run `python3 -m benchexec.check_cgroups`, the script hangs until I interrupt it and I get the following output:

```
Error while starting 'sh' in '.': [Errno 2] No such file or directory: '/sys/fs/cgroup/blkio/docker/4292901c6aff83e88b83328e6da7457b2ef8c41e8e6a52c80644029163955a1f/benchmark_llmxao0q/blkio.throttle.io_service_bytes'.
python3 -m benchexec.check_cgroups^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire() 
KeyboardInterrupt:
```

**Docker Desktop version** 
24.0.7, build afdd53b.

**WSL info**
`
WSL version: 2.0.14.0
Kernel version: 5.15.133.1-1
WSLg version: 1.0.59
MSRDC version: 1.2.4677
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19045.3930
`

**CGroups version** 
v1 (The file `/sys/fs/cgroup/cgroup.controllers` doesn't exist in the container, I checked as instructed in https://github.com/sosy-lab/benchexec/blob/main/doc/INSTALL.md#setting-up-cgroups).

Please note that the same container works normally on Ubuntu 20.04 VMs, so the issue seems specific to Docker Desktop.

**Comment by ysabih2** [comment]
@PhilippWendler Thanks for the reply.
```
# python3 -m benchexec.check_cgroups --no-thread
CRITICAL: Error while starting 'sh' in '.': [Errno 2] No such file or directory: '/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559d437bb559a99fea1f6a8/benchmark_tbykjqaf/blkio.throttle.io_service_bytes'.
^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire() 
KeyboardInterrupt:
```

```
# runexec --debug --no-container echo test
2024-01-18 13:56:21 - DEBUG - This is runexec 3.20.
2024-01-18 13:56:21 - DEBUG - Analyzing /proc/mounts and /proc/self/cgroup for determining cgroups.
2024-01-18 13:56:21 - DEBUG - Available Cgroups: {'cpuset': '/sys/fs/cgroup/cpuset/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'cpu': '/sys/fs/cgroup/cpu/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'cpuacct': '/sys/fs/cgroup/cpuacct/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'blkio': '/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'memory': '/sys/fs/cgroup/memory/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'devices': '/sys/fs/cgroup/devices/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'freezer': '/sys/fs/cgroup/freezer/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'net_cls': '/sys/fs/cgroup/net_cls/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'perf_event': '/sys/fs/cgroup/perf_event/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'net_prio': '/sys/fs/cgroup/net_prio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'hugetlb': '/sys/fs/cgroup/hugetlb/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'pids': '/sys/fs/cgroup/pids/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8'}
2024-01-18 13:56:21 - DEBUG - Available Cgroups: {'blkio': '/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_oitxmosd'}
2024-01-18 13:56:21 - DEBUG - Available Cgroups: {'cpuacct': '/sys/fs/cgroup/cpuacct/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_aw8r5579'}
2024-01-18 13:56:21 - DEBUG - Available Cgroups: {'freezer': '/sys/fs/cgroup/freezer/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_vf8fhuop'}
2024-01-18 13:56:21 - DEBUG - Available Cgroups: {'memory': '/sys/fs/cgroup/memory/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_1qhx8bwx'}
2024-01-18 13:56:21 - DEBUG - Available Cgroups: {'cpuset': '/sys/fs/cgroup/cpuset/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark__3c2fcch'}
2024-01-18 13:56:21 - DEBUG - List of available CPU cores is [0, 1, 2, 3, 4, 5, 6, 7].
2024-01-18 13:56:21 - DEBUG - List of available memory nodes is [0].
2024-01-18 13:56:21 - INFO - Starting command echo test
2024-01-18 13:56:21 - INFO - Writing output to output.log
2024-01-18 13:56:21 - DEBUG - Setting up cgroups for run.
2024-01-18 13:56:21 - DEBUG - Available Cgroups: {'blkio': '/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_as2opi9l', 'cpuacct': '/sys/fs/cgroup/cpuacct/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_kmxb_p4b', 'freezer': '/sys/fs/cgroup/freezer/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_q20e5qpk', 'memory': '/sys/fs/cgroup/memory/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_02tnyfxq'}
2024-01-18 13:56:21 - DEBUG - Created cgroups {'/sys/fs/cgroup/cpuacct/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_kmxb_p4b', '/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_as2opi9l', '/sys/fs/cgroup/memory/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_02tnyfxq', '/sys/fs/cgroup/freezer/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_q20e5qpk'}.
2024-01-18 13:56:21 - DEBUG - Using additional environment {}.
2024-01-18 13:56:21 - DEBUG - Starting process.
2024-01-18 13:56:21 - DEBUG - Executing run with $HOME and $TMPDIR below /tmp/BenchExec_run_ycf063yt.
2024-01-18 13:56:21 - DEBUG - Waiting for process echo with pid 167
2024-01-18 13:56:21 - DEBUG - Energy measurement terminated with return code 1
2024-01-18 13:56:21 - DEBUG - energy measurement stderr: cpu-energy-meter: Could not open /dev/cpu/0/msr: No such file or directory
2024-01-18 13:56:21 - DEBUG - energy measurement stderr: Cannot access RAPL!
2024-01-18 13:56:21 - DEBUG - Process terminated, exit code 0.
2024-01-18 13:56:21 - DEBUG - Getting cgroup measurements.
2024-01-18 13:56:21 - CRITICAL - Error while starting 'echo' in '.': [Errno 2] No such file or directory: '/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_as2opi9l/blkio.throttle.io_service_bytes'.
2024-01-18 13:56:21 - DEBUG - Source of this OSError is:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/benchexec/runexecutor.py", line 749, in execute_run
    return self._execute(
  File "/usr/lib/python3/dist-packages/benchexec/runexecutor.py", line 963, in _execute
    self._get_cgroup_measurements(cgroups, ru_child, result)
  File "/usr/lib/python3/dist-packages/benchexec/runexecutor.py", line 1079, in _get_cgroup_measurements
    result["blkio-read"], result["blkio-write"] = cgroups.read_io_stat()
  File "/usr/lib/python3/dist-packages/benchexec/cgroupsv1.py", line 545, in read_io_stat
    for blkio_line in self.get_file_lines(self.IO, blkio_bytes_file):
  File "/usr/lib/python3/dist-packages/benchexec/cgroups.py", line 209, in get_file_lines
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_as2opi9l/blkio.throttle.io_service_bytes'
terminationreason=failed
```

```
# runexec --debug --no-container --cores 0 echo test
2024-01-18 13:57:06 - DEBUG - This is runexec 3.20.
2024-01-18 13:57:06 - DEBUG - Analyzing /proc/mounts and /proc/self/cgroup for determining cgroups.
2024-01-18 13:57:06 - DEBUG - Available Cgroups: {'cpuset': '/sys/fs/cgroup/cpuset/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'cpu': '/sys/fs/cgroup/cpu/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'cpuacct': '/sys/fs/cgroup/cpuacct/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'blkio': '/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'memory': '/sys/fs/cgroup/memory/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'devices': '/sys/fs/cgroup/devices/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'freezer': '/sys/fs/cgroup/freezer/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'net_cls': '/sys/fs/cgroup/net_cls/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'perf_event': '/sys/fs/cgroup/perf_event/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'net_prio': '/sys/fs/cgroup/net_prio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'hugetlb': '/sys/fs/cgroup/hugetlb/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8', 'pids': '/sys/fs/cgroup/pids/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8'}
2024-01-18 13:57:06 - DEBUG - Available Cgroups: {'blkio': '/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_m6p0tbg5'}
2024-01-18 13:57:06 - DEBUG - Available Cgroups: {'cpuacct': '/sys/fs/cgroup/cpuacct/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_c7o6ajdx'}
2024-01-18 13:57:06 - DEBUG - Available Cgroups: {'freezer': '/sys/fs/cgroup/freezer/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_sgsax9dw'}
2024-01-18 13:57:06 - DEBUG - Available Cgroups: {'memory': '/sys/fs/cgroup/memory/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_6cksjp23'}
2024-01-18 13:57:06 - DEBUG - Available Cgroups: {'cpuset': '/sys/fs/cgroup/cpuset/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_3vs3rjif'}
2024-01-18 13:57:06 - DEBUG - List of available CPU cores is [0, 1, 2, 3, 4, 5, 6, 7].
2024-01-18 13:57:06 - DEBUG - List of available memory nodes is [0].
2024-01-18 13:57:06 - INFO - Starting command echo test
2024-01-18 13:57:06 - INFO - Writing output to output.log
2024-01-18 13:57:06 - DEBUG - Setting up cgroups for run.
2024-01-18 13:57:06 - DEBUG - Available Cgroups: {'blkio': '/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_f08woj8u', 'cpuacct': '/sys/fs/cgroup/cpuacct/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_klmdmodx', 'freezer': '/sys/fs/cgroup/freezer/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_cwilf5ra', 'memory': '/sys/fs/cgroup/memory/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_rmzwqsk9', 'cpuset': '/sys/fs/cgroup/cpuset/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_xwcciwev'}
2024-01-18 13:57:06 - DEBUG - Created cgroups {'/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_f08woj8u', '/sys/fs/cgroup/cpuacct/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_klmdmodx', '/sys/fs/cgroup/freezer/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_cwilf5ra', '/sys/fs/cgroup/cpuset/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_xwcciwev', '/sys/fs/cgroup/memory/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_rmzwqsk9'}.
2024-01-18 13:57:06 - DEBUG - Using cpu cores [0].
2024-01-18 13:57:06 - DEBUG - Using additional environment {}.
2024-01-18 13:57:06 - DEBUG - Starting process.
2024-01-18 13:57:06 - DEBUG - Executing run with $HOME and $TMPDIR below /tmp/BenchExec_run_249u4q93.
2024-01-18 13:57:06 - DEBUG - Waiting for process echo with pid 175
2024-01-18 13:57:06 - DEBUG - Process terminated, exit code 0.
2024-01-18 13:57:06 - DEBUG - Getting cgroup measurements.
2024-01-18 13:57:06 - CRITICAL - Error while starting 'echo' in '.': [Errno 2] No such file or directory: '/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_f08woj8u/blkio.throttle.io_service_bytes'.
2024-01-18 13:57:06 - DEBUG - Source of this OSError is:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/benchexec/runexecutor.py", line 749, in execute_run
    return self._execute(
  File "/usr/lib/python3/dist-packages/benchexec/runexecutor.py", line 963, in _execute
    self._get_cgroup_measurements(cgroups, ru_child, result)
  File "/usr/lib/python3/dist-packages/benchexec/runexecutor.py", line 1079, in _get_cgroup_measurements
    result["blkio-read"], result["blkio-write"] = cgroups.read_io_stat()
  File "/usr/lib/python3/dist-packages/benchexec/cgroupsv1.py", line 545, in read_io_stat
    for blkio_line in self.get_file_lines(self.IO, blkio_bytes_file):
  File "/usr/lib/python3/dist-packages/benchexec/cgroups.py", line 209, in get_file_lines
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/benchmark_f08woj8u/blkio.throttle.io_service_bytes'
terminationreason=failed
```

```
# ls -l /sys/fs/cgroup/ /sys/fs/cgroup/blkio/ /sys/fs/cgroup/blkio/docker/ /sys/fs/cgroup/blkio/docker/*/
/sys/fs/cgroup/:
total 0
dr-xr-xr-x 19 root root 0 Jan 18 13:29 blkio
dr-xr-xr-x 19 root root 0 Jan 18 13:29 cpu
dr-xr-xr-x 19 root root 0 Jan 18 13:29 cpuacct
dr-xr-xr-x 19 root root 0 Jan 18 13:29 cpuset
dr-xr-xr-x 26 root root 0 Jan 18 13:29 devices
dr-xr-xr-x 20 root root 0 Jan 18 13:29 freezer
dr-xr-xr-x 19 root root 0 Jan 18 13:29 hugetlb
dr-xr-xr-x 26 root root 0 Jan 18 13:29 memory
dr-xr-xr-x 19 root root 0 Jan 18 13:29 misc
dr-xr-xr-x 19 root root 0 Jan 18 13:29 net_cls
dr-xr-xr-x 19 root root 0 Jan 18 13:29 net_prio
dr-xr-xr-x 19 root root 0 Jan 18 13:29 perf_event
dr-xr-xr-x 26 root root 0 Jan 18 13:29 pids
dr-xr-xr-x 19 root root 0 Jan 18 13:29 rdma
dr-xr-xr-x 27 root root 0 Jan 18 13:29 systemd
dr-xr-xr-x 28 root root 0 Jan 18 13:29 unified

/sys/fs/cgroup/blkio/:
total 0
drwxr-xr-x 2 root root 0 Jan 18 13:29 01-docker
drwxr-xr-x 2 root root 0 Jan 18 13:29 artifactory
drwxr-xr-x 2 root root 0 Jan 18 13:29 binfmt
--w------- 1 root root 0 Jan 18 13:29 blkio.reset_stats    
-rw-r--r-- 1 root root 0 Jan 18 13:29 cgroup.clone_children
-rw-r--r-- 1 root root 0 Jan 18 13:29 cgroup.procs
-r--r--r-- 1 root root 0 Jan 18 13:29 cgroup.sane_behavior 
drwxr-xr-x 2 root root 0 Jan 18 13:29 container-filesystem 
drwxr-xr-x 2 root root 0 Jan 18 13:29 devenv-service       
drwxr-xr-x 2 root root 0 Jan 18 13:29 diagnosticsd
drwxr-xr-x 5 root root 0 Jan 18 13:29 docker
drwxr-xr-x 2 root root 0 Jan 18 13:57 kubepods
-rw-r--r-- 1 root root 0 Jan 18 13:29 notify_on_release    
drwxr-xr-x 2 root root 0 Jan 18 13:29 oom-tracer
drwxr-xr-x 2 root root 0 Jan 18 13:29 otel-collector       
drwxr-xr-x 2 root root 0 Jan 18 13:57 podruntime
-rw-r--r-- 1 root root 0 Jan 18 13:29 release_agent        
drwxr-xr-x 2 root root 0 Jan 18 13:29 sntpc
drwxr-xr-x 2 root root 0 Jan 18 13:29 socks
drwxr-xr-x 2 root root 0 Jan 18 13:57 systemreserved
-rw-r--r-- 1 root root 0 Jan 18 13:29 tasks
drwxr-xr-x 2 root root 0 Jan 18 13:29 trim-after-delete
drwxr-xr-x 2 root root 0 Jan 18 13:29 volume-contents
drwxr-xr-x 2 root root 0 Jan 18 13:29 vpnkit-forwarder

/sys/fs/cgroup/blkio/docker/:
total 0
drwxr-xr-x 2 root root 0 Jan 18 13:29 033699b67a177ad9c73a22fa8a9a6fbdb4be3bfe572b4914d38a3ef47cec4fc8
drwxr-xr-x 7 root root 0 Jan 18 13:30 06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8
--w------- 1 root root 0 Jan 18 13:57 blkio.reset_stats
drwxr-xr-x 2 root root 0 Jan 18 13:29 c54589802f620bfb71ddb6eba46107d4de306cd05a8a52f501bd58e1d29a94b2
-rw-r--r-- 1 root root 0 Jan 18 13:57 cgroup.clone_children
-rw-r--r-- 1 root root 0 Jan 18 13:57 cgroup.procs
-rw-r--r-- 1 root root 0 Jan 18 13:57 notify_on_release
-rw-r--r-- 1 root root 0 Jan 18 13:57 tasks

/sys/fs/cgroup/blkio/docker/033699b67a177ad9c73a22fa8a9a6fbdb4be3bfe572b4914d38a3ef47cec4fc8/:
total 0
--w------- 1 root root 0 Jan 18 13:57 blkio.reset_stats
-rw-r--r-- 1 root root 0 Jan 18 13:57 cgroup.clone_children
-rw-r--r-- 1 root root 0 Jan 18 13:29 cgroup.procs
-rw-r--r-- 1 root root 0 Jan 18 13:57 notify_on_release
-rw-r--r-- 1 root root 0 Jan 18 13:57 tasks

/sys/fs/cgroup/blkio/docker/06264953147b728eec566f84c4f1b3a96b6c3aa18cbfd437bb559a99fea1f6a8/:
total 0
drwx------ 2 root root 0 Jan 18 13:55 benchmark_31ji8do5
drwx------ 2 root root 0 Jan 18 13:54 benchmark_8de_b_4t
drwx------ 2 root root 0 Jan 18 13:56 benchmark_as2opi9l
drwx------ 2 root root 0 Jan 18 13:57 benchmark_f08woj8u
drwx------ 2 root root 0 Jan 18 13:32 benchmark_tbykjqaf
--w------- 1 root root 0 Jan 18 13:57 blkio.reset_stats
-rw-r--r-- 1 root root 0 Jan 18 13:57 cgroup.clone_children
-rw-r--r-- 1 root root 0 Jan 18 13:30 cgroup.procs
-rw-r--r-- 1 root root 0 Jan 18 13:57 notify_on_release
-rw-r--r-- 1 root root 0 Jan 18 13:57 tasks

/sys/fs/cgroup/blkio/docker/c54589802f620bfb71ddb6eba46107d4de306cd05a8a52f501bd58e1d29a94b2/:
total 0
--w------- 1 root root 0 Jan 18 13:57 blkio.reset_stats
-rw-r--r-- 1 root root 0 Jan 18 13:57 cgroup.clone_children
-rw-r--r-- 1 root root 0 Jan 18 13:29 cgroup.procs
-rw-r--r-- 1 root root 0 Jan 18 13:57 notify_on_release
-rw-r--r-- 1 root root 0 Jan 18 13:57 tasks
```

**Comment by PhilippWendler** [comment]
Thanks, this was helpful! I think I identified the problem (Docker Desktop provides weird cgroup setup with less than the usual features) and have committed a workaround. Please test with the recent development version and if there are still problems, please reopen.

**Comment by ysabih2** [comment]
@PhilippWendler Thank you very much! The fix works.
