### ISSUE TITLE
Failed to configure container, mounting /tmp/ocitest.../proc

### ISSUE THREAD

**Issue by charmoniumQ** [sosy-lab/benchexec#988]
How should I go about debugging

```
ubuntu@upcrc1:~$ containerexec --read-only-dir / ls
2024-02-11 23:02:01,095 - INFO - Starting command ls
2024-02-11 23:02:01,150 - CRITICAL - Failed to configure container with operation 'raise OSError(errno, msg)': [Errno 2] mount(b'/tmp/ocitest1446117452/proc', b'/tmp/BenchExec_run_8ztzyg31/mount/tmp/ocitest1446117452/proc', None, 282624, None) failed: No such file or directory
Cannot execute ls: execution in container failed, check log for details.
```

However, `--keep-tmp` makes this work.

**Comment by PhilippWendler** [comment]
Thanks for reporting this!

For debugging, the most useful thing would be to run with `--debug` and report the output here.
You can also show what `findmnt` prints.

Some more information about the context would also be good:
- BenchExec version
- OS (which version of Ubuntu?, which kernel)
- anything special about the system, e.g., are you running inside a container?

**Comment by charmoniumQ** [comment]
<summary>
The `--debug` output of a broken run
<details><pre><code>
containerexec --read-only-dir / --debug ls
2024-02-12 07:24:26 - DEBUG - This is containerexec 3.20.
2024-02-12 07:24:26 - INFO - Starting command ls
2024-02-12 07:24:26 - DEBUG - Available Cgroups: {}
2024-02-12 07:24:26 - DEBUG - Starting process.
2024-02-12 07:24:26 - DEBUG - Child: child process of RunExecutor with PID 2584574 started
2024-02-12 07:24:26 - DEBUG - Parent: child process of RunExecutor with PID 2584574 started.
2024-02-12 07:24:26 - DEBUG - Failed to make b'/tmp/BenchExec_run_2xavekul/mount/home/benchexec' a bind mount: [Errno 2] mount(b'/tmp/BenchExec_run_2xavekul/mount/home/benchexec', b'/tmp/BenchExec_run_2xavekul/mount/home/benchexec', None, 4096, None) failed: No such file or directory
2024-02-12 07:24:26 - DEBUG - Mounting '/' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/dev' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/dev/pts' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/dev/shm' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/dev/hugepages' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/dev/mqueue' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/run' as hidden
2024-02-12 07:24:26 - DEBUG - [Errno 16] umount(b'/tmp/BenchExec_run_2xavekul/mount/run') failed: Device or resource busy
2024-02-12 07:24:26 - DEBUG - Mounting '/sys' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/sys/kernel/security' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/sys/fs/cgroup' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/sys/fs/pstore' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/sys/fs/bpf' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/sys/kernel/debug' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/sys/kernel/tracing' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/sys/fs/fuse/connections' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/sys/kernel/config' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/proc' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/core18/2409' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/core18/2538' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/core20/1518' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/docker/1779' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/core20/1405' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/lxd/22923' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/snapd/16010' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/go/9848' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/kata-containers/2446' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/snapd/16292' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/boot' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/tmp/ocitest1446117452/proc' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/go/10164' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/core22/864' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/core22/1033' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/snap/snapd/20671' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/var/lib/lxcfs' as read-only
2024-02-12 07:24:26 - DEBUG - Mounting '/tmp' as hidden
2024-02-12 07:24:26 - DEBUG - [Errno 16] umount(b'/tmp/BenchExec_run_2xavekul/mount/tmp') failed: Device or resource busy
2024-02-12 07:24:26 - DEBUG - Mounting '/tmp/ocitest1446117452/proc' as read-only
2024-02-12 07:24:26 - CRITICAL - Failed to configure container with operation 'raise OSError(errno, msg)': [Errno 2] mount(b'/tmp/ocitest1446117452/proc', b'/tmp/BenchExec_run_2xavekul/mount/tmp/ocitest1446117452/proc', None, 282624, None) failed: No such file or directory
2024-02-12 07:24:26 - DEBUG - Waiting for process ls with pid 2584574
2024-02-12 07:24:26 - DEBUG - Parent: child process of RunExecutor with PID 2584574 terminated with return value 128.
2024-02-12 07:24:26 - DEBUG - Process terminated, exit code 0.
2024-02-12 07:24:26 - DEBUG - Cleaning up temporary directory.
2024-02-12 07:24:26 - ERROR - execution in container failed, check log for details
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/benchexec/containerexecutor.py", line 956, in _start_execution_in_container
    grandchild_pid = int(os.read(from_grandchild, 10))
ValueError: invalid literal for int() with base 10: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/benchexec/containerexecutor.py", line 297, in main
    result = executor.execute_run(
  File "/usr/lib/python3/dist-packages/benchexec/containerexecutor.py", line 470, in execute_run
    pid, result_fn = self._start_execution(
  File "/usr/lib/python3/dist-packages/benchexec/containerexecutor.py", line 539, in _start_execution
    result = self._start_execution_in_container(
  File "/usr/lib/python3/dist-packages/benchexec/containerexecutor.py", line 960, in _start_execution_in_container
    check_child_exit_code()
  File "/usr/lib/python3/dist-packages/benchexec/containerexecutor.py", line 913, in check_child_exit_code
    raise BenchExecException(
benchexec.BenchExecException: execution in container failed, check log for details
Cannot execute ls: execution in container failed, check log for details.
</code></pre></details>
</summary>

Here is a visualization of the diff between the broken run (left) and the non-broken run (right).
![image](https://github.com/sosy-lab/benchexec/assets/928570/eca90d85-3c73-48f6-98e3-a1d5f9b93beb)

```
ubuntu@upcrc1:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
```

Only unique thing about this machine is that is is virtualized in a way that is mostly opaque to me.

**Comment by PhilippWendler** [comment]
Wait, you have it sometimes working and sometimes not? What is the difference between these runs, when does it work and when not?

What is this `/tmp/ocitest1446117452` directory? Do you have mounts there? What does `findmnt` say?

Please try with `--hidden-dir /tmp/ocitest1446117452`.

**Comment by charmoniumQ** [comment]
> Wait, you have it sometimes working and sometimes not? What is the difference between these runs, when does it work and when not?

Slight misunderstanding: the command deterministically fails, but when change it to add `--keep-tmp-dir`, it deterministically succeeds. I've diffed logs from the two runs.

> What is this `/tmp/ocitest1446117452` directory? Do you have mounts there? What does findmnt say?

A dev, proc, and sys. It looks like a chroot of a container.

findmnt reports the following.

```
└─/tmp/ocitest1446117452             /dev/mapper/ubuntu--vg-ubuntu--lv[/tmp/ocitest1446117452]
                                                      ext4        rw,relatime
  ├─/tmp/ocitest1446117452/proc      proc             proc        rw,nosuid,nodev,noexec,relatime
  ├─/tmp/ocitest1446117452/dev       tmpfs            tmpfs       rw,nosuid,noexec,size=65536k,mode=755,inode64
  │ ├─/tmp/ocitest1446117452/dev/pts devpts           devpts      rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=666
  │ ├─/tmp/ocitest1446117452/dev/shm shm              tmpfs       rw,nosuid,nodev,noexec,relatime,size=65536k,inode64
  │ └─/tmp/ocitest1446117452/dev/mqueue
  │                                  mqueue           mqueue      rw,nosuid,nodev,noexec,relatime
  └─/tmp/ocitest1446117452/sys       sysfs            sysfs       ro,nosuid,nodev,noexec,relatime
```

> Please try with `--hidden-dir /tmp/ocitest1446117452`.

Same error.

**Comment by PhilippWendler** [comment]
I found the bug, we treated all proc mounts in a special way that should apply only to `/proc`. Thus having a proc mounted below a hidden directory (such as `/tmp` in default mode) did not work.

Can you please try branch `988-ignore-other-proc-mounts` of BenchExec to test my fix?
